apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: hbs
  lifecycle: production
  subcomponentOf:
    - component:hbs-backend
  type: library
  owner: ""
metadata:
  name: hbs-frontend
  annotations:
    license: Apache-2.0
    playbook.io.nrs.gov.bc.ca/clientId: ""
    playbook.io.nrs.gov.bc.ca/unitTestsPath: ""
    playbook.io.nrs.gov.bc.ca/postDeployTestsPath: ""
    playbook.io.nrs.gov.bc.ca/publishArtifactSuffix: dist
    playbook.io.nrs.gov.bc.ca/deployOnPrem: false
    github.com/project-slug: bcgov/nr-hbs
    playbook.io.nrs.gov.bc.ca/ociArtifacts: ""
    composer.io.nrs.gov.bc.ca/generators: gh-nodejs-build,backstage
    playbook.io.nrs.gov.bc.ca/nodeVersion: "24"
  description: HBS Frontend
  title: HBS Frontend
