<?xml version="1.0" encoding="UTF-8"?>
<!-- Harvest Billing System: Intra Site Events Request Schema - Version 1.0 -->
<xs:schema targetNamespace="gov.bc.ca/forests/hbs/v2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="gov.bc.ca/forests/hbs/v2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:element name="hbs-request">
		<xs:annotation>
			<xs:documentation>Intra Site Events Request</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="xml-ise-request-header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ise-request-id">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:totalDigits value="12"/>
										<xs:fractionDigits value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="datetime-created">
								<xs:simpleType>
									<xs:restriction base="xs:dateTime">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="doc-count">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:totalDigits value="6"/>
										<xs:fractionDigits value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="requestor-email" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="128"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requestor-relationship" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
										<xs:maxLength value="8"/>									
										<xs:enumeration value="Public"/>
										<xs:enumeration value="Ministry"/>
										<xs:enumeration value="Industry"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requestor-client" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="8"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requestor-client-location" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-timber-mark" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-cut-block" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-scale-site" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-from-event-date" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:date">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-to-event-date" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:date">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-from-load-number" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-to-load-number" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-from-weigh-slip" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="requested-to-weigh-slip" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="fine-print" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="2048"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>	
				<xs:element name="intra-site-events" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ise-request-id">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:totalDigits value="12"/>
										<xs:fractionDigits value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ddn">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="13"/>
										<xs:maxLength value="13"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ddv">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:totalDigits value="2"/>
										<xs:fractionDigits value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="transport-type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
										<xs:maxLength value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="document-type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="2"/>
										<xs:maxLength value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>										
							<xs:element name="event-type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="2"/>
										<xs:maxLength value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>										
							<xs:element name="version-status">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
										<xs:maxLength value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="scale-site">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
							<xs:element name="event-date">
								<xs:simpleType>
									<xs:restriction base="xs:date">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>										
							<xs:element name="timber-mark" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>										
							<xs:element name="cut-block" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="load-arrival-number" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>	
							<xs:element name="weigh-slip" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>	
							<xs:element name="scaler-licence" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>										
							<xs:element name="return-number" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:totalDigits value="4"/>
										<xs:fractionDigits value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>	
							<xs:element name="net-volume" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:totalDigits value="9"/>
										<xs:fractionDigits value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="log-count" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:decimal">
										<xs:totalDigits value="4"/>
										<xs:fractionDigits value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>							
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
