<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by JC MacArthur (Sierra Systems Group Inc) -->
<!-- Harvest Billing System: Scale Data Submission Schema - Version 1.0 (Appendix B Version 3.1e) February 27, 2002 -->
<!--Copyright (c) 2002, B.C. Ministry of Forests All rights reserved-->
<xs:schema targetNamespace="gov.bc.ca/forests/hbs/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="gov.bc.ca/forests/hbs/v1" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:element name="HBS">
		<xs:annotation>
			<xs:documentation>HBS Scale Data Submission Schema - Version 1</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="transmission">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="BatchCount" type="xs:integer"/>
							<xs:element name="Type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="P"/>
										<xs:enumeration value="T"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Creator">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="WSB" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="WSBDocument" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="PS"/>
													<xs:enumeration value="SS"/>
													<xs:enumeration value="RS"/>
													<xs:enumeration value="PD"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="WSCommon"/>
										<xs:element ref="WSWeights"/>
										<xs:element ref="WSSource"/>
										<xs:element name="FieldScaleFlag">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
													<xs:enumeration value="Y"/>
													<xs:enumeration value="N"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="FieldScaleDeckID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PSY">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="8"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OutgoingLDSNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Destination" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="SampleType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
													<xs:enumeration value="C"/>
													<xs:enumeration value="N"/>
													<xs:enumeration value="F"/>
													<xs:enumeration value="S"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="DocID"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="WSR" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="WSRDocument" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="RT"/>
													<xs:enumeration value="RR"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="WSCommon"/>
										<xs:element ref="WSWeights"/>
										<xs:element ref="WSSource"/>
										<xs:element name="FieldScaleFlag">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
													<xs:enumeration value="Y"/>
													<xs:enumeration value="N"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="FieldScaleDeckID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PSY">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="8"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OutgoingLDSNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Destination" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="DocID"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="WSO" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="WSODocument" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="4R"/>
													<xs:enumeration value="DP"/>
													<xs:enumeration value="CU"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="WSCommon"/>
										<xs:element name="PSY" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="8"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OutgoingLDSNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="IncomingLDSNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Destination" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="TransportIdentifier" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="16"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Source" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="7"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="DocID"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PPS" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="PPSDocument" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="PS"/>
													<xs:enumeration value="FD"/>
													<xs:enumeration value="RT"/>
													<xs:enumeration value="RR"/>
													<xs:enumeration value="CS"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="PSCommon"/>
										<xs:element name="LoadArrivalNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="IncomingLDSNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="TransportIdentifier" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="16"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Source">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="7"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="CutblockID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="FieldScaleFlag">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="1"/>
													<xs:minLength value="1"/>
													<xs:enumeration value="Y"/>
													<xs:enumeration value="N"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="FieldScaleDeckID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="WeighSlipNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OriginatingScaleSiteNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="SplitLoad" minOccurs="0"/>
										<xs:element name="Beachcomb" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="1"/>
													<xs:enumeration value="N"/>
													<xs:enumeration value="Y"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="CheckScale" minOccurs="0"/>
										<xs:element ref="PSMeasure"/>
									</xs:sequence>
									<xs:attributeGroup ref="DocID"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PSS" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="PSSDocument" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="CS"/>
													<xs:enumeration value="SS"/>
													<xs:enumeration value="RS"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="PSCommon"/>
										<xs:element name="LoadArrivalNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="IncomingLDSNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="TransportIdentifier" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="16"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Source">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="7"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PSY">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="8"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="WeighSlipNumber">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="SampleWeight">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minInclusive value="1"/>
													<xs:maxInclusive value="999999"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OriginatingScaleSiteNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="CheckScale" minOccurs="0"/>
										<xs:element ref="PSMeasure"/>
									</xs:sequence>
									<xs:attributeGroup ref="DocID"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="POT" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="POTDocument" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="4R"/>
													<xs:enumeration value="CU"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="PSCommon"/>
										<xs:element name="LoadArrivalNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="IncomingLDSNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="TransportIdentifier" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="16"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Source" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="7"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="SplitLoad" minOccurs="0"/>
									</xs:sequence>
									<xs:attributeGroup ref="DocID"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ARL" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="ARLEntry" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Arrival" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ArrivalDate">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:length value="8"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="LoadArrivalNumber">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
																<xs:maxLength value="10"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="IncomingLDSNumber">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
																<xs:maxLength value="10"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="TransportIdentifier">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
																<xs:maxLength value="16"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Source">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="7"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Scale" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ScaleDate">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:length value="8"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="PrimaryScalerLicence">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
																<xs:maxLength value="4"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="PrimaryScalerReturnNumber">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="0"/>
																<xs:maxInclusive value="9999"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element ref="SplitLoad" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="FieldScaleFlag" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
													<xs:enumeration value="N"/>
													<xs:enumeration value="Y"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="FieldScaleDeckID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="CutblockID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="WeighSlipNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OriginatingScaleSiteNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="PS"/>
													<xs:enumeration value="B4"/>
													<xs:enumeration value="4R"/>
													<xs:enumeration value="TD"/>
													<xs:enumeration value="FD"/>
													<xs:enumeration value="RR"/>
													<xs:enumeration value="RS"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ScaleSite">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DPL" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="BatchHeader"/>
							<xs:element name="DPLEntry" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DepartureDate">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="8"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OutgoingLDSNumber">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Destination">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="20"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="DepartureNumber">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OutgoingTransportIdentifier">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="16"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="EventType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:length value="2"/>
													<xs:enumeration value="DP"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ScaleSite">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WSCommon">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ScaleSite">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ScaleDate">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="8"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ScaleTime">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="235959"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="WeighSlipNumber" type="xs:unsignedLong"/>
				<xs:element name="PrimaryScalerLicence">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SecondaryScalerLicence" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Comment" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="200"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="Software"/>
				<xs:element ref="EC_Digest"/>
				<xs:element ref="EC_Signature" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WSWeights">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Gross">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="1"/>
							<xs:maxInclusive value="999999"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Tare">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="999999"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SampleDeduction" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="999999"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WSSource">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Source">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="7"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="IncomingLDSNumber">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="TransportIdentifier">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="16"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CutblockID">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PSCommon">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ScaleSite">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ScaleDate">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="8"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="PrimaryScalerLicence">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="PrimaryScalerReturnNumber">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="9999"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SecondaryScalerLicence" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="Software"/>
				<xs:element ref="EC_Digest"/>
				<xs:element ref="EC_Signature" minOccurs="0"/>
				<xs:element name="Comment" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="200"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SplitLoad">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ParcelID">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="9"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ParcelCount">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="9"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PSMeasure">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Log" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LogNumber">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="9999"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TM" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="NM" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="1"/>
										<xs:enumeration value="N"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="SP">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:length value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="GR">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="LT">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="999"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TP">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="999"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="BT">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="999"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="NetVolume">
								<xs:simpleType>
									<xs:restriction base="xs:unsignedInt">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="999999"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="DefectCount">
								<xs:simpleType>
									<xs:restriction base="xs:unsignedInt">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="9"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Defect" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DefectNumber">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:maxInclusive value="9"/>
													<xs:minInclusive value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="DefectCode">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:whiteSpace value="preserve"/>
													<xs:minLength value="1"/>
													<xs:maxLength value="2"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="DefectVolume">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minInclusive value="0"/>
													<xs:maxInclusive value="999999"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="DefectFmtDesc">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="40"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="LogCount">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="9999"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ScaleMethod">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="1"/>
							<xs:enumeration value="G"/>
							<xs:enumeration value="N"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CheckScale">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="OriginalScalerLicence">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="OriginalScalerReturnNumber">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="9999"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CheckReplacesOriginal">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:length value="1"/>
							<xs:enumeration value="Y"/>
							<xs:enumeration value="N"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="DocID">
		<xs:attribute name="DDN" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:maxLength value="13"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="DV" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:totalDigits value="2"/>
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="99"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:element name="BatchHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ScaleSite">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FromScaleDate">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="8"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ToScaleDate">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="8"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SubmitterBatchID" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="DocumentCount" type="xs:integer"/>
				<xs:element name="BatchControlTotal" type="xs:integer"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Software">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SoftwareProduct">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="12"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SoftwareVersion">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SoftwareRevision">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EC_Digest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Method">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="CRC32"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EC_HT">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EC_Signature">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SigningScalerLicence">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EC_AKEHT">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="-2147483648"/>
							<xs:maxInclusive value="2147483647"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Method">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="CRC32"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
